(function (window) {
  "use strict";

  const PUBLIC_CONFIG = Object.freeze(window.TPT_APP_CONFIG || {});
  const APP = {
    name: "Trợ lý Tổng phụ trách Đội",
    version: PUBLIC_CONFIG.APP_VERSION || "3.1.0-rc.1",
    schema: Number(PUBLIC_CONFIG.SCHEMA_VERSION || 15),
    dbName: PUBLIC_CONFIG.DB_NAME || "TPT_DOI_DB",
    appId: PUBLIC_CONFIG.APP_ID || "vn.giaoducso40.tpt.thcs.standard",
    schoolProfileId:
      PUBLIC_CONFIG.SCHOOL_PROFILE_ID || "thcs-local-profile-001",
    defaultSchoolProfileId:
      PUBLIC_CONFIG.SCHOOL_PROFILE_ID || "thcs-local-profile-001",
    schoolName: PUBLIC_CONFIG.SCHOOL_NAME || "TRƯỜNG",
    schoolLevel: PUBLIC_CONFIG.SCHOOL_LEVEL || "TH-THCS",
    repositoryName: String(PUBLIC_CONFIG.REPOSITORY_NAME || "").trim(),
    basePath: String(PUBLIC_CONFIG.BASE_PATH || "./").trim() || "./",
    backupFormat: "TPT-BACKUP-3",
    buildId: PUBLIC_CONFIG.BUILD_ID || "20260831-api",
  };
  const STORES = [
    "profiles",
    "schools",
    "campuses",
    "school_years",
    "semesters",
    "school_weeks",
    "grades",
    "classes",
    "class_groups",
    "homeroom_teachers",
    "plans",
    "plan_targets",
    "tasks",
    "task_check_items",
    "task_dependencies",
    "calendar_events",
    "activity_categories",
    "activities",
    "activity_classes",
    "activity_check_items",
    "criteria_sets",
    "criteria_groups",
    "criteria",
    "weekly_score_sheets",
    "score_grader_assignments",
    "teacher_class_assignments",
    "score_entries",
    "score_evidence",
    "ranking_snapshots",
    "team_units",
    "team_positions",
    "team_members",
    "training_records",
    "programs",
    "program_results",
    "commendations",
    "documents",
    "attachments",
    "equipment",
    "equipment_transactions",
    "report_templates",
    "generated_reports",
    "audit_logs",
    "app_settings",
    "config_categories",
    "config_items",
    "custom_field_definitions",
    "document_folders",
    "document_links",
    "file_versions",
    "migration_logs",
    "task_templates",
    "score_component_versions",
    "license_events",
    "operation_journal",
    "internal_snapshots",
    "form_drafts",
    "restore_staging",
    "backup_handles",
    "backup_records",
    "year_transition_logs",
    "report_packages",
  ];
  const SYSTEM_STORES = new Set([
    "operation_journal",
    "internal_snapshots",
    "form_drafts",
    "restore_staging",
    "backup_handles",
    "backup_records",
    "migration_logs",
    "audit_logs",
    "license_events",
  ]);
  const SNAPSHOT_EXCLUDED_STORES = new Set([
    ...SYSTEM_STORES,
    "attachments",
    "file_versions",
  ]);
  const EXTERNAL_BACKUP_EXCLUDED_STORES = new Set([
    "operation_journal",
    "internal_snapshots",
    "form_drafts",
    "restore_staging",
    "backup_handles",
  ]);

  window.TPTAppModules = window.TPTAppModules || {};
  window.TPTAppModules.schema = Object.freeze({
    PUBLIC_CONFIG,
    APP,
    STORES,
    SYSTEM_STORES,
    SNAPSHOT_EXCLUDED_STORES,
    EXTERNAL_BACKUP_EXCLUDED_STORES,
  });
})(window);
