(function () {
  "use strict";

  const NAV = [
    ["dashboard", "⌂", "Tổng quan"],
    ["today", "◷", "Hôm nay"],
    ["plans", "▤", "Kế hoạch"],
    ["tasks", "✓", "Công việc và checklist"],
    ["calendar", "▦", "Lịch hoạt động"],
    ["scores", "★", "Thi đua lớp"],
    ["activities", "⚑", "Hoạt động Đội"],
    ["organization", "♟", "Tổ chức Liên đội"],
    ["programs", "◇", "Rèn luyện – phong trào"],
    ["commendations", "✦", "Khen thưởng"],
    ["documents", "▧", "Hồ sơ – minh chứng"],
    ["equipment", "◫", "Thiết bị Đội"],
    ["reports", "▥", "Báo cáo"],
    ["assistant", "◎", "Trợ lý tổng hợp"],
    ["backup", "⇄", "Sao lưu – khôi phục"],
    ["account", "♙", "Tài khoản của tôi"],
    ["users", "♜", "Quản lý người dùng"],
    ["settings", "⚙", "Thiết lập"],
  ];

  const ENTITY = {
    plans: {
      title: "Kế hoạch",
      store: "plans",
      desc: "Kế hoạch năm học, học kỳ, tháng và tuần.",
      fields: [
        ["code", "Mã kế hoạch", "text", 1],
        ["name", "Tên kế hoạch", "text", 1],
        [
          "level",
          "Cấp kế hoạch",
          "select",
          1,
          "year: Năm học|semester: Học kỳ|month: Tháng|week: Tuần",
        ],
        ["start_date", "Bắt đầu", "date", 1],
        ["end_date", "Kết thúc", "date", 1],
        ["objectives", "Mục tiêu", "textarea", 1],
        ["targets", "Chỉ tiêu đo được", "textarea"],
        ["basis", "Căn cứ/văn bản liên quan", "textarea"],
        ["coordination", "Đơn vị phối hợp", "text"],
        ["resources", "Nguồn lực", "text"],
        ["risks", "Rủi ro và phương án", "textarea"],
        [
          "status",
          "Trạng thái",
          "select",
          1,
          "draft: Dự thảo|active: Đang thực hiện|finished: Đã kết thúc",
        ],
        ["progress", "Tiến độ (%)", "number"],
      ],
    },
    activities: {
      title: "Hoạt động Đội",
      store: "activities",
      desc: "Tổ chức, theo dõi hoạt động và phương án an toàn.",
      fields: [
        ["name", "Tên hoạt động", "text", 1],
        [
          "category",
          "Nhóm hoạt động",
          "select",
          1,
          "Truyền thống – đạo đức|Học tập – sáng tạo|Kỹ năng sống – an toàn|Văn nghệ – thể thao|Môi trường|Tình nguyện – nhân đạo|Rèn luyện đội viên|Xây dựng tổ chức Đội",
        ],
        ["theme", "Chủ điểm", "text"],
        ["date", "Ngày tổ chức", "date", 1],
        ["location", "Địa điểm", "text", 1],
        ["leader", "Người phụ trách", "text", 1],
        ["participants", "Đối tượng/quy mô", "text"],
        ["objectives", "Mục tiêu", "textarea"],
        ["safety", "Phương án an toàn", "textarea", 1],
        ["backup_plan", "Phương án dự phòng", "textarea"],
        ["result", "Kết quả sau hoạt động", "textarea"],
        [
          "status",
          "Trạng thái",
          "select",
          1,
          "planned: Dự kiến|active: Đang thực hiện|finished: Đã kết thúc",
        ],
      ],
    },
    organization: {
      title: "Tổ chức Liên đội",
      store: "team_members",
      desc: "Ban Chỉ huy, đội nghi lễ, phát thanh măng non và đội nhóm.",
      fields: [
        ["name", "Họ và tên", "text", 1],
        ["internal_code", "Mã nội bộ", "text"],
        ["class_name", "Lớp", "text", 1],
        [
          "unit",
          "Đội/ban",
          "select",
          1,
          "Ban Chỉ huy Liên đội|Ban Chỉ huy Chi đội|Đội nghi lễ|Phát thanh măng non|Đội tự quản|Câu lạc bộ",
        ],
        ["position", "Chức vụ", "text", 1],
        ["term", "Nhiệm kỳ", "text", 1],
        ["training", "Kết quả bồi dưỡng", "textarea"],
      ],
    },
    programs: {
      title: "Rèn luyện – phong trào",
      store: "program_results",
      desc: "Theo dõi chương trình, chuyên hiệu, công trình và việc tốt.",
      fields: [
        ["name", "Tên chương trình/chuyên hiệu", "text", 1],
        ["scope", "Đối tượng/lớp", "text", 1],
        ["result", "Kết quả công nhận", "text"],
        ["recognized_date", "Ngày công nhận", "date"],
        ["activity", "Hoạt động tham gia", "text"],
        ["evidence", "Minh chứng/ghi chú", "textarea"],
        [
          "status",
          "Trạng thái",
          "select",
          1,
          "draft: Đang theo dõi|approved: Đã công nhận",
        ],
      ],
    },
    commendations: {
      title: "Khen thưởng",
      store: "commendations",
      desc: "Hồ sơ khen thưởng tập thể và cá nhân.",
      fields: [
        ["award_type", "Loại khen thưởng", "text", 1],
        ["level", "Cấp khen thưởng", "text", 1],
        ["recipient", "Đối tượng", "text", 1],
        ["achievement", "Thành tích", "textarea", 1],
        ["date", "Thời gian", "date"],
        ["related", "Hoạt động/kỳ thi đua liên quan", "text"],
        [
          "approval_status",
          "Trạng thái xét duyệt",
          "select",
          1,
          "draft: Dự thảo|review: Chờ duyệt|approved: Đã duyệt",
        ],
        ["decision", "Quyết định", "text"],
        ["notes", "Ghi chú", "textarea"],
      ],
    },
    documents: {
      title: "Hồ sơ – minh chứng",
      store: "documents",
      desc: "Thư viện hồ sơ theo năm học và bản ghi liên quan.",
      fields: [
        ["name", "Tên hồ sơ", "text", 1],
        [
          "type",
          "Loại",
          "select",
          1,
          "Kế hoạch|Hoạt động|Thi đua|Tổ chức Đội|Khen thưởng|Báo cáo",
        ],
        ["document_no", "Số hiệu", "text"],
        ["issuer", "Đơn vị ban hành", "text"],
        ["date", "Ngày văn bản", "date"],
        ["related", "Bản ghi liên quan", "text"],
        ["tags", "Thẻ", "text"],
        ["description", "Mô tả/đường dẫn tệp cục bộ", "textarea"],
        [
          "status",
          "Trạng thái",
          "select",
          1,
          "draft: Bản nháp|approved: Đã xác nhận",
        ],
      ],
    },
    equipment: {
      title: "Thiết bị Đội",
      store: "equipment",
      desc: "Kiểm kê, mượn–trả và chuẩn bị thiết bị cho sự kiện.",
      fields: [
        ["name", "Tên thiết bị/vật tư", "text", 1],
        ["code", "Mã", "text", 1],
        ["group", "Nhóm", "text"],
        ["quantity", "Số lượng", "number", 1],
        ["unit", "Đơn vị tính", "text", 1],
        [
          "condition",
          "Tình trạng",
          "select",
          1,
          "Tốt|Cần sửa|Hỏng|Đang mượn",
        ],
        ["location", "Nơi lưu", "text"],
        ["inventory_date", "Ngày kiểm kê", "date"],
        ["activity", "Hoạt động đang sử dụng", "text"],
        ["notes", "Ghi chú hư hỏng/bổ sung", "textarea"],
      ],
    },
  };

  const SETTINGS_TABS = [
    ["school", "Thông tin trường"],
    ["context", "Cơ sở – năm học – học kỳ – tuần"],
    ["classes", "Lớp và giáo viên chủ nhiệm"],
    ["competition", "Cấu hình thi đua"],
    ["activities", "Danh mục hoạt động"],
    ["tasks", "Công việc và checklist"],
    ["documents", "Hồ sơ – tài liệu"],
    ["team", "Tổ chức Đội – phong trào"],
    ["awards", "Khen thưởng"],
    ["equipment", "Thiết bị"],
    ["reports", "Báo cáo và mẫu in"],
    ["appearance", "Giao diện"],
    ["data", "Dữ liệu – sao lưu"],
    ["security", "Khóa phiên và bảo mật"],
  ];

  const SETTINGS_CONFIG_KEYS = {
    activities: ["activity_type", "calendar_type"],
    tasks: ["task_group", "task_status", "priority"],
    documents: ["document_type", "document_status"],
    team: ["team_group", "team_position", "program_type", "specialty"],
    awards: ["award_type", "award_level"],
    equipment: ["equipment_group", "equipment_condition", "unit"],
    reports: ["report_type", "report_template"],
    context: ["plan_type", "plan_level", "plan_status"],
  };

  const CONFIG_DEFINITIONS = [
    [
      "plan_type",
      "Loại kế hoạch",
      ["Năm học", "Học kỳ", "Tháng", "Tuần", "Chuyên đề"],
    ],
    [
      "plan_level",
      "Cấp kế hoạch",
      ["Toàn trường", "Liên đội", "Chi đội", "Cơ sở"],
    ],
    [
      "plan_status",
      "Trạng thái kế hoạch",
      ["Dự thảo", "Đang thực hiện", "Đã kết thúc"],
    ],
    [
      "activity_type",
      "Loại hoạt động",
      [
        "Giáo dục truyền thống – đạo đức",
        "Học tập – sáng tạo",
        "Kỹ năng sống – an toàn",
        "Văn nghệ – thể thao",
        "Môi trường",
        "Tình nguyện – nhân đạo",
        "Rèn luyện đội viên",
        "Xây dựng tổ chức Đội",
        "Hoạt động theo chủ điểm",
        "Hoạt động phối hợp",
      ],
    ],
    [
      "task_group",
      "Nhóm công việc",
      ["Tuần", "Tháng", "Học kỳ", "Năm học", "Đột xuất"],
    ],
    [
      "task_status",
      "Trạng thái công việc",
      [
        "Chưa làm",
        "Đang làm",
        "Chờ phối hợp",
        "Chờ duyệt",
        "Hoàn thành",
        "Tạm dừng",
      ],
    ],
    ["priority", "Mức ưu tiên", ["Thấp", "Bình thường", "Cao", "Khẩn"]],
    [
      "calendar_type",
      "Loại sự kiện lịch",
      ["Hoạt động Đội", "Họp", "Tập huấn", "Hạn hồ sơ", "Thi đua"],
    ],
    [
      "document_type",
      "Loại hồ sơ",
      [
        "Kế hoạch",
        "Hoạt động",
        "Thi đua",
        "Tổ chức Đội",
        "Rèn luyện",
        "Khen thưởng",
        "Báo cáo",
        "Thiết bị",
      ],
    ],
    [
      "document_status",
      "Trạng thái hồ sơ",
      ["Bản nháp", "Đã xác nhận", "Lưu trữ"],
    ],
    [
      "team_group",
      "Nhóm tổ chức/đội/ban",
      [
        "Ban Chỉ huy Liên đội",
        "Ban Chỉ huy Chi đội",
        "Đội nghi lễ",
        "Phát thanh măng non",
        "Đội tự quản",
        "Câu lạc bộ",
      ],
    ],
    [
      "team_position",
      "Chức vụ",
      [
        "Liên đội trưởng",
        "Liên đội phó",
        "Chi đội trưởng",
        "Chi đội phó",
        "Ủy viên",
      ],
    ],
    [
      "program_type",
      "Loại chương trình rèn luyện",
      [
        "Rèn luyện đội viên",
        "Chuyên hiệu",
        "Công trình măng non",
        "Việc tốt",
      ],
    ],
    [
      "specialty",
      "Chuyên hiệu",
      [
        "An toàn giao thông",
        "Chăm học",
        "Nghệ sĩ nhỏ tuổi",
        "Nhà sinh học nhỏ tuổi",
      ],
    ],
    [
      "award_type",
      "Loại khen thưởng",
      ["Giấy khen", "Tuyên dương", "Chứng nhận", "Phần thưởng"],
    ],
    [
      "award_level",
      "Cấp khen thưởng",
      ["Chi đội", "Liên đội", "Nhà trường", "Cấp trên"],
    ],
    [
      "equipment_group",
      "Nhóm thiết bị",
      ["Nghi lễ", "Âm thanh", "Trang trí", "Thể thao", "Văn phòng"],
    ],
    [
      "equipment_condition",
      "Tình trạng thiết bị",
      ["Tốt", "Cần sửa", "Hỏng", "Đang mượn"],
    ],
    ["unit", "Đơn vị tính", ["Cái", "Bộ", "Chiếc", "Hộp", "Cuộn"]],
    [
      "report_type",
      "Loại báo cáo",
      [
        "Công tác tuần",
        "Thi đua tuần",
        "Công việc",
        "Hoạt động",
        "Thiết bị",
        "Hồ sơ",
      ],
    ],
    [
      "report_template",
      "Mẫu báo cáo",
      ["Mẫu ngắn", "Mẫu đầy đủ", "Bảng tổng hợp"],
    ],
  ];

  window.TPTAppModules = window.TPTAppModules || {};
  window.TPTAppModules.catalog = Object.freeze({
    NAV,
    ENTITY,
    SETTINGS_TABS,
    SETTINGS_CONFIG_KEYS,
    CONFIG_DEFINITIONS,
  });
})();
